#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-R.oo
Version  : 1.27.0
Release  : 57
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/R.oo_1.27.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/R.oo_1.27.0.tar.gz
Summary  : R Object-Oriented Programming with or without References
Group    : Development/Tools
License  : LGPL-2.1+
Requires: R-R.methodsS3
BuildRequires : R-R.methodsS3
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%prep
%setup -q -n R.oo
pushd ..
cp -a R.oo buildavx2
popd
pushd ..
cp -a R.oo buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1731650280

%install
export SOURCE_DATE_EPOCH=1731650280
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/R.oo/CITATION
/usr/lib64/R/library/R.oo/DESCRIPTION
/usr/lib64/R/library/R.oo/INDEX
/usr/lib64/R/library/R.oo/Meta/Rd.rds
/usr/lib64/R/library/R.oo/Meta/features.rds
/usr/lib64/R/library/R.oo/Meta/hsearch.rds
/usr/lib64/R/library/R.oo/Meta/links.rds
/usr/lib64/R/library/R.oo/Meta/nsInfo.rds
/usr/lib64/R/library/R.oo/Meta/package.rds
/usr/lib64/R/library/R.oo/NAMESPACE
/usr/lib64/R/library/R.oo/NEWS.md
/usr/lib64/R/library/R.oo/R/R.oo
/usr/lib64/R/library/R.oo/R/R.oo.rdb
/usr/lib64/R/library/R.oo/R/R.oo.rdx
/usr/lib64/R/library/R.oo/WORDLIST
/usr/lib64/R/library/R.oo/doc/Bengtsson.pdf
/usr/lib64/R/library/R.oo/help/AnIndex
/usr/lib64/R/library/R.oo/help/R.oo.rdb
/usr/lib64/R/library/R.oo/help/R.oo.rdx
/usr/lib64/R/library/R.oo/help/aliases.rds
/usr/lib64/R/library/R.oo/help/paths.rds
/usr/lib64/R/library/R.oo/html/00Index.html
/usr/lib64/R/library/R.oo/html/R.css
/usr/lib64/R/library/R.oo/misc/ASCII.R
/usr/lib64/R/library/R.oo/misc/Exception.R
/usr/lib64/R/library/R.oo/tests/ASCII.R
/usr/lib64/R/library/R.oo/tests/BasicObject.R
/usr/lib64/R/library/R.oo/tests/Class.R
/usr/lib64/R/library/R.oo/tests/Exception.R
/usr/lib64/R/library/R.oo/tests/Interface.R
/usr/lib64/R/library/R.oo/tests/InternalErrorException.reportBug.R
/usr/lib64/R/library/R.oo/tests/Object.R
/usr/lib64/R/library/R.oo/tests/Object.finalize,noattach.R
/usr/lib64/R/library/R.oo/tests/Object.finalize,onoff.R
/usr/lib64/R/library/R.oo/tests/Object.finalize.R
/usr/lib64/R/library/R.oo/tests/Package.R
/usr/lib64/R/library/R.oo/tests/Package.unload.R
/usr/lib64/R/library/R.oo/tests/StaticMethodsAndNamespaces.R
/usr/lib64/R/library/R.oo/tests/abort.R
/usr/lib64/R/library/R.oo/tests/attachLocally.Object.R
/usr/lib64/R/library/R.oo/tests/equals.R
/usr/lib64/R/library/R.oo/tests/extend.default.R
/usr/lib64/R/library/R.oo/tests/getConstructorS3.R
/usr/lib64/R/library/R.oo/tests/hashCode.R
/usr/lib64/R/library/R.oo/tests/isBeingCreated.Class.R
/usr/lib64/R/library/R.oo/tests/ll.R
/usr/lib64/R/library/R.oo/tests/local.R
/usr/lib64/R/library/R.oo/tests/objectSize.R
/usr/lib64/R/library/R.oo/tests/throw.R
/usr/lib64/R/library/R.oo/tests/trim.R
/usr/lib64/R/library/R.oo/tests/typeOfClass.R
/usr/lib64/R/library/R.oo/tests/zzz.Object.finalize,reentrant.R
