#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-R.oo
Version  : 1.22.0
Release  : 25
URL      : https://cran.r-project.org/src/contrib/R.oo_1.22.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/R.oo_1.22.0.tar.gz
Summary  : R Object-Oriented Programming with or without References
Group    : Development/Tools
License  : LGPL-2.1
Requires: R-R.methodsS3
BuildRequires : R-R.methodsS3
BuildRequires : buildreq-R
BuildRequires : util-linux

%description
No detailed description available

%prep
%setup -q -c -n R.oo

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571895689

%install
export SOURCE_DATE_EPOCH=1571895689
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library R.oo
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library R.oo
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library R.oo
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc R.oo || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/R.oo/CITATION
/usr/lib64/R/library/R.oo/DESCRIPTION
/usr/lib64/R/library/R.oo/INDEX
/usr/lib64/R/library/R.oo/Meta/Rd.rds
/usr/lib64/R/library/R.oo/Meta/features.rds
/usr/lib64/R/library/R.oo/Meta/hsearch.rds
/usr/lib64/R/library/R.oo/Meta/links.rds
/usr/lib64/R/library/R.oo/Meta/nsInfo.rds
/usr/lib64/R/library/R.oo/Meta/package.rds
/usr/lib64/R/library/R.oo/NAMESPACE
/usr/lib64/R/library/R.oo/NEWS
/usr/lib64/R/library/R.oo/R/R.oo
/usr/lib64/R/library/R.oo/R/R.oo.rdb
/usr/lib64/R/library/R.oo/R/R.oo.rdx
/usr/lib64/R/library/R.oo/doc/Bengtsson.pdf
/usr/lib64/R/library/R.oo/help/AnIndex
/usr/lib64/R/library/R.oo/help/R.oo.rdb
/usr/lib64/R/library/R.oo/help/R.oo.rdx
/usr/lib64/R/library/R.oo/help/aliases.rds
/usr/lib64/R/library/R.oo/help/paths.rds
/usr/lib64/R/library/R.oo/html/00Index.html
/usr/lib64/R/library/R.oo/html/R.css
/usr/lib64/R/library/R.oo/misc/ASCII.R
/usr/lib64/R/library/R.oo/misc/Exception.R
/usr/lib64/R/library/R.oo/tests/ASCII.R
/usr/lib64/R/library/R.oo/tests/BasicObject.R
/usr/lib64/R/library/R.oo/tests/Class.R
/usr/lib64/R/library/R.oo/tests/Exception.R
/usr/lib64/R/library/R.oo/tests/Interface.R
/usr/lib64/R/library/R.oo/tests/InternalErrorException.reportBug.R
/usr/lib64/R/library/R.oo/tests/Object.R
/usr/lib64/R/library/R.oo/tests/Object.finalize,noattach.R
/usr/lib64/R/library/R.oo/tests/Object.finalize,onoff.R
/usr/lib64/R/library/R.oo/tests/Object.finalize.R
/usr/lib64/R/library/R.oo/tests/Package.R
/usr/lib64/R/library/R.oo/tests/Package.unload.R
/usr/lib64/R/library/R.oo/tests/StaticMethodsAndNamespaces.R
/usr/lib64/R/library/R.oo/tests/abort.R
/usr/lib64/R/library/R.oo/tests/attachLocally.Object.R
/usr/lib64/R/library/R.oo/tests/equals.R
/usr/lib64/R/library/R.oo/tests/extend.default.R
/usr/lib64/R/library/R.oo/tests/getConstructorS3.R
/usr/lib64/R/library/R.oo/tests/hashCode.R
/usr/lib64/R/library/R.oo/tests/isBeingCreated.Class.R
/usr/lib64/R/library/R.oo/tests/ll.R
/usr/lib64/R/library/R.oo/tests/local.R
/usr/lib64/R/library/R.oo/tests/objectSize.R
/usr/lib64/R/library/R.oo/tests/throw.R
/usr/lib64/R/library/R.oo/tests/trim.R
/usr/lib64/R/library/R.oo/tests/typeOfClass.R
/usr/lib64/R/library/R.oo/tests/zzz.Object.finalize,reentrant.R
